import { Resend } from 'resend';

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed.' });
  }

  if (!process.env.RESEND_API_KEY) {
    return res.status(500).json({ error: 'Missing RESEND_API_KEY environment variable.' });
  }

  const resend = new Resend(process.env.RESEND_API_KEY);

  const { name, email, subject, message } = req.body ?? {};

  if (!name || !email || !message) {
    return res.status(400).json({ error: 'Name, email, and message are required.' });
  }

  try {
    const data = await resend.emails.send({
      from: 'Kritika Mandale - Portfolio Inquiry <onboarding@resend.dev>',
      to: 'kritikamandale@gmail.com',
      replyTo: email,
      subject: `New Professional Inquiry: ${subject || 'Connection Request'} - ${name}`,
      html: `
        <div style="font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 15px; color: #333; line-height: 1.6;">
          <h2 style="margin-top: 0; font-size: 20px; color: #111;">New Inquiry from Your Portfolio</h2>

          <p style="color: #555;">You have received a new message via your professional portfolio. The details of the inquiry are securely logged below.</p>

          <p style="margin-top: 20px;">
            <strong>Sender Name:</strong> ${name}<br>
            <strong>Email Address:</strong> <a href="mailto:${email}" style="color: #0056b3;">${email}</a><br>
            <strong>Subject:</strong> ${subject || 'No Subject Provided'}
          </p>

          <p style="margin-top: 25px;"><strong>Message Transcript:</strong></p>
          <p style="white-space: pre-wrap; margin-top: 5px; color: #222;">${message}</p>

          <br>
          <hr style="border: none; border-top: 1px solid #ccc; margin: 20px 0;">
          <p style="color: #777; font-size: 13px; margin: 0;">
            Automated communication generated by Kritika Mandale's Portfolio Platform.<br>
            Reply directly to this email to respond to the sender.
          </p>
        </div>
      `,
    });

    if (data.error) {
      return res.status(400).json({ error: data.error.message || 'Failed to send message.' });
    }

    return res.status(200).json({ success: true, data });
  } catch (error) {
    console.error('Contact function error:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
}